### ISSUE TITLE
Want to contribute, havin' a hard time

### ISSUE THREAD

**Issue by mklnln** [TimDaub/react-simple-knob#12]
Hey Tim,

I'm building a sequencer using React and found your knob in a google search. It works well, except I'd like to style it differently. I'd like to rotate it 45deg clockwise and remove the text around it. I'm a bit new with modifying modules like this. I'm able to rotate the knob with CSS after it renders, but am unable to remove the text.

Is it possible to do either of these things? I was trying to load just the basic project you have but was unable to get it running. A friend who was helping me thought that it might have been an issue with compatibility around NodeJS or Rollup versions.

Anyways, if you have any insight that would be greatly appreciated. Thanks!

**Comment by mklnln** [comment]
By the way, the error I got was:

```
npm run dev

> react-simple-knob@0.0.6 dev C:\Users\Admin\Documents\Code Projex\react-simple-knob\react-simple-knob
> npm-run-all --parallel watch serve


> react-simple-knob@0.0.6 watch C:\Users\Admin\Documents\Code Projex\react-simple-knob\react-simple-knob
> rollup -c -w


> react-simple-knob@0.0.6 serve C:\Users\Admin\Documents\Code Projex\react-simple-knob\react-simple-knob
> serve dist

[!] TypeError: Unknown file extension ".json" for C:\Users\Admin\Documents\Code Projex\react-simple-knob\react-simple-knob\package.json
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for C:\Users\Admin\Documents\Code Projex\react-simple-knob\react-simple-knob\package.json      
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)     
    at async Promise.all (index 5)
    at async link (internal/modules/esm/module_job.js:83:9)


UPDATE AVAILABLE The latest version of `serve` is 14.2.0

   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serving!                                        │
   │                                                   │
   │   - Local:            http://localhost:5000       │
   │   - On Your Network:  http://192.168.1.121:5000   │
   │                                                   │
   │   Copied local address to clipboard!              │
   │                                                   │
   └───────────────────────────────────────────────────┘
```

**Comment by TimDaub** [comment]
Hey, sorry for taking so long to respond, I was traveling.
The project is fairly old and without updated code and so I imagine you have to update it into 2023 before making any meaningful changes? Another option is to just use node 10 or 12, which are likely the versions this project was created in. E.g. the .json file ending issue looks like it'd show up in a newer version of node.
